export const ONBOARDING_KEY = '@MOBILIZADOR-SHOWONBOARDING';
export const TOKEN_KEY = '@MOBILIZADOR-TOKEN';

export const OFFLINE_CREATED_ROUTES = '@MOBILIZADOR-OFFLINE-CREATED-ROUTES';
export const OFFLINE_UPDATED_ROUTES = '@MOBILIZADOR-OFFLINE-UPDATED-ROUTES';
export const OFFLINE_UPDATED_ROUTE_EVENTS =
  '@MOBILIZADOR-OFFLINE-UPDATED-ROUTE-EVENT';
export const OFFLINE_CANCELED_ROUTE_EVENTS =
  '@MOBILIZADOR-OFFLINE-CANCELED-ROUTE-EVENT';

export const LAST_SYNC_DATE = '@MOBILIZADOR-LAST-SYNC-DATE';
